version: "3"

services:
  nginx:
    build:
      context: .
      dockerfile: ./nginx/Dockerfile
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./certbot/Letsencrypt:/etc/letsencrypt

volumes:
  nginx-letsencrypt:
